### ISSUE TITLE
Word Count not working properly

### ISSUE THREAD

**Issue by a-ciacaicedo** [RyanWils/my-note#1]
Word counter function has several issues.
On Firefox:

- Word Count is a number ahead after space is pressed, but before anything is typed.
![image](https://user-images.githubusercontent.com/49992710/65095265-8024f580-d98e-11e9-908d-44309eca1f13.png)

- When a line is deleted completely, not cleared, the counter displays 1 instead of 0
![image](https://user-images.githubusercontent.com/49992710/65095159-0c82e880-d98e-11e9-9d8c-f9e223214b14.png)

On Chrome:

- Hitting space more than twice will begin counting space as words.
![image](https://user-images.githubusercontent.com/49992710/65095871-e3b02280-d990-11e9-8f47-e95ff9c99c0f.png)

On both Chrome and Firefox:

- Word count will not count words that have been entered after space is hit, or after space has been hit and a single space has been pressed
![image](https://user-images.githubusercontent.com/49992710/65095714-510f8380-d990-11e9-98a9-33ee4d1eb43d.png)

**Comment by RyanWils** [comment]
Great catch, if you would like to fix it go ahead
