### ISSUE TITLE
Textarea requires a scroll bar

### ISSUE THREAD

**Issue by MeisterRed** [RyanWils/my-note#5]
Hi Ryan,
I've noticed that if the user were to type a lot of words or add a lot of lines to the textarea, the text ends up going off the area and over the buttons.

![image](https://user-images.githubusercontent.com/32404189/65376036-6541d200-dc69-11e9-963c-38b55f6b83ed.png)

I would like to add a scrollbar to the textarea to fix this issue

**Comment by RyanWils** [comment]
Great bug catch, if you would like to fix it please go ahead
